### ISSUE TITLE
Mensagem de erro para carregamento das bases não pode ser genérica

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#102]
Atualmente a ferramenta apresenta o seguinte erro para carregamento de bases: **Erro ao importar base**. 

A ferramenta deve ser capaz de apresentar ao usuário uma justificativa para a mensagem de erro apresentada. 
Ela deve especificar a causa.
Se o usuário não colocou um nome para a base ela deve indicar esse erro, o mesmo vale para a descrição ou qualquer outro erro apresentado no processo

**Comment by ojvictor** [comment]
@guerra É necessário traduzir a mensagem de erro "Please fill out this field" para português.

**Comment by mgonc** [comment]
isso é um helper do browser, se você usa o browser em português vai estar em português.

**Comment by ojvictor** [comment]
@mgonc Não teriamos como orientar essa mensagem de acordo com o idioma da ferramenta? Independente do browser?
