### ISSUE TITLE
Tabela de percentagem média sobrepõe a visualização de analise de sentimentos

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#112]
O frame da visualização da análise de sentimentos está estático. E a tabela com a percentagem média está sobrepondo a mesma
![average_table_overlap_sentimental](https://user-images.githubusercontent.com/6419508/26877555-a7de0ff8-4b60-11e7-83cb-0bd9caef302e.png)

**Comment by pedrobernardina** [comment]
Resolvido por #96

**Comment by michelboaventura** [comment]
@pedrobernardina e @ojvictor, isso está resolvido mesmo? Porque acho que #96 já está merjado no que o joão está testando

**Comment by pedrobernardina** [comment]
Esta é minha branch mb_layout_rebased 

![image](https://user-images.githubusercontent.com/15324745/26939546-04ec29e4-4c4e-11e7-92a5-d34848d66a98.png)
