### ISSUE TITLE
Subistituir o termo "This is the visualization title" pelo nome da visualização

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#113]
Nas visualizações de analise de sentimentos e matriz de correlação, o termo "this is the visualization title" deve ser substituído pelo nome da visualização.
![print_visualization_title](https://user-images.githubusercontent.com/6419508/26877762-4e9f7cfa-4b61-11e7-933b-b04a9623aa87.png)

**Comment by pedrobernardina** [comment]
Resolvido por #118
