### ISSUE TITLE
Melhorar o css da lista apresentada na visualização de análise de sentimentos

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#115]
Melhorar o css da lista que acompanha a visualização de análise de sentimentos. O aspecto do label da tabela, o tamanho das linhas, a fonte da letra devem ser modificados de acordo com os elementos que faziam parte da ferramenta com o css anterior by lsl

**Comment by pedrobernardina** [comment]
Resolvido por #96

**Comment by michelboaventura** [comment]
@pedrobernardina e @ojvictor, isso está resolvido mesmo? Porque acho que #96 já está merjado no que o joão está testando.

**Comment by ojvictor** [comment]
@michelboaventura não esta resolvido na versão que esta rodando na staging que eu acessei hoje de manhã.
