### ISSUE TITLE
Melhorar as proporçoes do tamanho das palavras na wordtree na página de visualização da consulta pública

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#119]
É necessário melhorar a proporção do tamanho das palavras na wordtree para que o resultado visual da mesma no frame das consultas publicas seja mais satisfátorio. 
Como a palavra do nodo raíz está muito grande a proporção de espaço em branco no e espaço com texto no frame não fica interessante para o resultado que se propõe. 
Talvez seja interessante mudar o tamanho do frame central ou melhorar o css para que a visualização seja mais harmoniosa. 
Outro aspecto que pode ser definido é colocar um scroll na parte superior do frame, permitindo que o usuário seja capaz de mover a visualização horizontalmente sem a necessidade de descer até o base vertical da pagina. 
![wordtree_public_visualization_issue](https://user-images.githubusercontent.com/6419508/26880617-5322af36-4b6b-11e7-9879-3be37c39178a.png)

**Comment by ojvictor** [comment]
@gfranciscani Não teriamos como diminuir o tamanho da palavra raíz da árvore?

**Comment by gfranciscani** [comment]
@ojvictor , claro. Farei isso asap!
