### ISSUE TITLE
Aumentar o tamanho do campo de pesquisa nas visualizações dos grafos nas consultas publicas

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#122]
O tamanho do campo de pesquisa poderia preencher todo o espaço entre os ícones de zoom e o botão que desabilita o highlight. 
![little_search_field](https://user-images.githubusercontent.com/6419508/26880812-0e5505b0-4b6c-11e7-8660-20f29018ec1d.png)

**Comment by guerra** [comment]
@gfranciscani reportou que existe um botão que aparece alí quando dá zoom. Caso aumente o campo de busca vai quebrar a visualização. @ojvictor

**Comment by ojvictor** [comment]
@guerra @gfranciscani Poderíamos aumentar o campo da busca no limite necessário para a visualização não quebrar?

**Comment by gfranciscani** [comment]
@ojvictor @guerra , o tamanho já está no máximo. Quando o usuário aplica o zoom, aparece um botão de RESET ZOOM que ocupa a parte restante.
