### ISSUE TITLE
O frame sobrepõe a legenda da visualização de matriz de correlação para visualizações publicas

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#123]
O frame atual que comporta a visualização da matriz de correlação está sobrepondo a legenda. 
![frame_overlap_mattrix_visu](https://user-images.githubusercontent.com/6419508/26881038-a178be9a-4b6c-11e7-90c6-6654ddb9cb3f.png)

**Comment by pedrobernardina** [comment]
O PR #96 mexeu em código relacionado às dimensões o canvas. Essas mudanças ainda não estão em staging. Favor testar com as novas mudanças.
