### ISSUE TITLE
Mudar algoritmo de ordenação para análise de sentimentos

### ISSUE THREAD

**Issue by pedrobernardina** [michelboaventura/mj_data_explorer#133]
O algoritmo sendo utilizado é o bubble. Mudar para o quicksort ou qualquer outro mais eficiente.

**Comment by ojvictor** [comment]
@pedrobernardina Tem alguma previsão? Como a tela está travando, seria interessante adicionar o mesmo indicador de processamentos que utilizamos no carregamento de outras visualizações. Geralmente utilizamos um para search tool e wordtree.

**Comment by michelboaventura** [comment]
@pedrobernardina, vocês implementaram bubble sort no algoritmo, serião? Me mostra onde está o código pra eu ver se a gente não usa o sort do javascript mesmo.

**Comment by pedrobernardina** [comment]
Porque quando pega a tabela retorna um HTML Collections, não um Array. Eu peguei essa solução pronta pra falar a verdade, e é mais fácil refazer (acho) usando d3.
