### ISSUE TITLE
Retirar o nome do filtro aparece sem formatação na página de visualizações publicas

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#136]
O nome do filtro aparece solto na tela de visualização pública.

![test_string_tittle_open_visualizations](https://user-images.githubusercontent.com/6419508/27136844-ababe9a6-50f2-11e7-8acb-43aaf1e49b0d.png)

**Comment by ojvictor** [comment]
![test_string_tittle_open_visualizations2](https://user-images.githubusercontent.com/6419508/27137120-76cf59b0-50f3-11e7-9062-e87f8f1d8f09.png)

**Comment by ojvictor** [comment]
Agora que eu entendi que o texto que aparece equivale a descrição do filtro criado. Estava achando que era uma mensagem solta na tela. Me desculpem.
Poderíamos de alguma forma indicar que se trata da descrição do filtro?
@mgonc o que você acha?

**Comment by guerra** [comment]
@ojvictor , o pessoal da marimbondo colocou assim. Se o texto fosse maior ficaria mais claro que é uma descrição.
