### ISSUE TITLE
Legendas cortadas no firefox

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#140]
@pedrobernardina @gfranciscani 
![firefox_label_cut](https://user-images.githubusercontent.com/6419508/27287350-ac8e9ef0-54d9-11e7-9088-4ba8ad57e83f.png)

**Comment by gfranciscani** [comment]
@ojvictor , tem como você me enviar o link para eu poder reproduzir? Tentei fazer aqui com outras bases e não consegui reproduzir o erro.

**Comment by gfranciscani** [comment]
@guerra confirmou o fechamento da issue. Não conseguimos reproduzir o erro.
