### ISSUE TITLE
Diminuir o tamanho da fonte para aviso de visualização sem resultados

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#146]
Diminuir a fonte e centralizar a mensagem de status.
![visu_status_error_too_big](https://user-images.githubusercontent.com/6419508/27483204-d2ab8e44-57fa-11e7-9dc0-a787d58fbfa3.png)

**Comment by guerra** [comment]
Além de diminuir temos que centralizar.
