### ISSUE TITLE
Erro na execução dos filtros

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#156]
Data do teste 29/06
O teste foi realizado após o deploy da aplicação pelo @guerra 

![error_execute_filter](https://user-images.githubusercontent.com/6419508/27694592-e2876e2e-5cc2-11e7-80d3-a11ccc52172d.png)

**Comment by michelboaventura** [comment]
@ojvictor, o PR https://github.com/michelboaventura/mj_data_explorer/pull/149 deixou o código mais restritivo quando aos dados que ele tratava e havia na base de staging um caso de comentários sem datasource vinculada, provavelmente devido a algum teste antigo. O que fiz foi basicamente dar uma limpada no banco, removendo esses casos e tudo parece que voltou a funcionar!

**Comment by ojvictor** [comment]
@michelboaventura Apaguei o filtro antigo e executei um novo como os mesmos parametros e continuou apresentando erros na execução. 

Para reproduzir erro:
Igual privacidade OU Igual pessoais

**Comment by michelboaventura** [comment]
@ojvictor, consegui reproduzir o erro usando "igual privacidade OU contém pessoais". Já corrigi e dei deploy. Mandei executar novamente o seu job que estava com problema e agora ele rodou!
