### ISSUE TITLE
Erro nos resultados da visualização de Co-ocorrência

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#159]
Esse exemplo está a planilha disponibilizada pelo Meira e os filtros criados serão utilizados na apresentação. 
Após gerar o seguinte filtro:
Contém anonim

Observei os seguintes aspectos nas visualizações de Co-ocorrência e Co-ocorrência FULL
1. Lentidão na geração da visualização
2. Para a visualização de Co-ocorrência aparece a legendas com os termos casados no filtro e a 
barra de sugestão funciona perfeitamente para os mesmos
![co_ocorrence_error_01](https://user-images.githubusercontent.com/6419508/27736332-215d1a74-5d7a-11e7-9998-e532fde7d35e.png)
3. Na visualização de Co-ocorrência FULL que por definição deveria apresentar todos os relacionamentos dos elementos, a legenda NÃO aparece  e a barra de pesquisa NÃO funciona. 
![co_ocorrence_error_02](https://user-images.githubusercontent.com/6419508/27736535-ec9e7df4-5d7a-11e7-8c9e-ada46a0c0baf.png)

**Comment by gfranciscani** [comment]
@ojvictor , acabei de checar a visualização. Vou responder às perguntas:

> _1. Lentidão na geração da visualização_

Mesmo sendo canvas, com essa quantidade de nós e arestas, é possível que a visualização fique lenta, por causa do processamentos da posição dos nós. 

> _2 e 3. Na visualização de Co-ocorrência FULL que por definição deveria apresentar todos os relacionamentos dos elementos, a legenda NÃO aparece e a barra de pesquisa NÃO funciona._

O problema não está na visualização, e sim no json que está vindo. A busca está funcionando perfeitamente, porém o json do grafo full não contém nenhum nó que possua a palavra "anonim".

@michelboaventura e @guerra , vocês sabem o que pode estar acontecendo?

**Comment by guerra** [comment]
@ojvictor , nós fizemos aquelas restrições de quantidade, pedindo uma busca menos abrangente.
