### ISSUE TITLE
Erro ao clicar no link para visualizar os resutados na aba Public Results

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#22]
Quando clicamos no link para visualizar os resultados dos jobs publicos, a aplicação redireciona a tela das visualizações para a landing page. 
O css aparece quebrado e quando clicamos em qualquer visualização, a aplicação redireciona para a landing page.

**Comment by mgonc** [comment]
@michelboaventura esse problema é aquele que temos que colocar a visualização passando pelo rails

**Comment by ojvictor** [comment]
@mgonc alguma atualização?

**Comment by michelboaventura** [comment]
A parte de visualizar os dados públicos foi implementada em https://github.com/michelboaventura/mj_data_explorer/pull/38
