### ISSUE TITLE
A identificação do filtro criado não aparece nas telas de visualização

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#23]
Foi requerido que a identificação do filtro que esta sendo acessado apareça em todas as telas das visualizações. 
Essa medida visa facilitar ao usuário a identificação de qual filtro as visualizações representam.

**Comment by ojvictor** [comment]
@michelboaventura alguma atualização?

**Comment by michelboaventura** [comment]
Corrigido em https://github.com/michelboaventura/mj_data_explorer/pull/39
