### ISSUE TITLE
Visualização participante-item crashando

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#26]
Algumas visualizações estão demorando para aparecer ou nem aparecem ( somente o gif loading)

**Comment by michelboaventura** [comment]
@ojvictor, me passa mais detalhes por favor. Qual visu em qual job?

**Comment by ojvictor** [comment]
Teste visualizar o grafo de participantes para o job: Lemonade T1: Public filter (População AND Proteção)

**Comment by michelboaventura** [comment]
@ojvictor, aparentemente a visu está é crashando e o div com aquele spinner não some.

@pedrobernardina, é a visu de participantes-itens com o json http://ceweb.ctweb.inweb.org.br/json/58f4b204b4a34d590c6e7119/part-item.json
