### ISSUE TITLE
Utilizar os nomes dos operadores lógicos ao invés de seus símbolos

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#27]
Padronizar as queries para que os termos EQUAL e NOT EQUALS apareçam nas sentenças ao invés !.

**Comment by michelboaventura** [comment]
Corrigido em https://github.com/michelboaventura/mj_data_explorer/pull/33

Porém os jobs já criados continuarão com o formato antigo.
