### ISSUE TITLE
WordTree: Problema com o scroll horizontal

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#28]
Algumas frases estão ultrapassando o limite horizontal da tela. Parece que ultrapassam o limite do scroll horizontal

![termo_longo](https://cloud.githubusercontent.com/assets/6419508/25132610/7ce5bcb8-2420-11e7-9f94-552ad93b655e.png)

**Comment by ojvictor** [comment]
@pedrobernardina @gfranciscani alguma atualização?

**Comment by gfranciscani** [comment]
Resolved!
