### ISSUE TITLE
WordTree: Artigos e preposições sendo considerados nodos

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#29]
Os artigos e preposições estão sendo considerados nodos. 
@michelboaventura este é o comportamento correto?
![artigos](https://cloud.githubusercontent.com/assets/6419508/25132783/09a8af02-2421-11e7-8c64-a18319147228.png)

**Comment by michelboaventura** [comment]
@ojvictor e @guerra, as duas formas são fáceis de fazer. Eu não removi propositalmente pra tentar manter a estrutura do texto, mas posso mudar sem problema. O que vocês acham?

**Comment by guerra** [comment]
Conforme conversei com o Adriano, estou fechando essa issue. Por enquanto deixaremos os artigos.
