### ISSUE TITLE
Visualizações com grafos não estão sendo geradas para filtros contendo EQUAL e NOT EQUAL

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#30]
Em todas os testes realizados com filtros EQUAL e NOT EQUAL não foram geradas visualizações de grafos. ( co-ocurrence, co-ocurrence full, participants )

**Comment by michelboaventura** [comment]
Quando for assim, coloca por favor o id do job pra eu não ter que sair procurando um por um.

**Comment by ojvictor** [comment]
http://ceweb.ctweb.inweb.org.br/job/58f60c7fb4a34d70f730e505/result
http://ceweb.ctweb.inweb.org.br/job/58f60cedb4a34d70f48622b7/result
http://ceweb.ctweb.inweb.org.br/job/58f60a95b4a34d70fac14276/result

**Comment by michelboaventura** [comment]
@ojvictor, o problema é que a memória da máquina acabou pq as consultas que vc fez geraram mtas linhas e lá só tem 4GB de RAM (no meu pc gastou 8GB pra rodar). Isso vai ser resolvido quando migrarmos para uma máquina maior.
