### ISSUE TITLE
WordTree: Frases com um único termo estão sendo considerada nodos

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#31]
Para alguns casos, frases com apenas um termo estão sendo considerados nodos. 
@michelboaventura Este comportamento está correto?
![1termo](https://cloud.githubusercontent.com/assets/6419508/25133155/3a5e647e-2422-11e7-9022-4249f487da47.png)

**Comment by michelboaventura** [comment]
É sim. Se você olhar o modelo que usamos como base a mesma coisa acontece: https://www.jasondavies.com/wordtree/?source=obama.inauguration.2013.txt&prefix=We
