### ISSUE TITLE
O job não retorna resultados para grafos para queries que usam EQUAL

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#35]
http://staging-ceweb.speed.dcc.ufmg.br/job/58f8a191f81fca3930f2f775/result
http://staging-ceweb.speed.dcc.ufmg.br/job/58f883c9f81fca3930f2f774/result
http://staging-ceweb.speed.dcc.ufmg.br/job/58f7b65ff81fca39338bf010/result

**Comment by michelboaventura** [comment]
@ojvictor, já corrigimos isso né?

**Comment by ojvictor** [comment]
Já corrigimos.
