### ISSUE TITLE
A aplicação quebra quando se tenta acessar/editar uma base de dados

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#36]
Ao acessar a aba Datasources, a ferramenta quebra ao clicar no link do nome, grupo ou tentar editar.

**Comment by mgonc** [comment]
Não consegui reporduzir o erro

**Comment by michelboaventura** [comment]
Corrigido em https://github.com/michelboaventura/mj_data_explorer/pull/37
