### ISSUE TITLE
Visualização: Corrigir o tipo de match dos termos sugeridos no grafo de co-ocorrencia. 

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#58]
O match dos termos sugeridos no campo de busca dos grafos de co-ocorrencia está definido como CONTAINS e não como EQUAL. 

Isso permite que ao procurar a palavra **privada**, os termos **privada** e **privadas** sejam marcados no grafo.

**Comment by michelboaventura** [comment]
@gfranciscani

**Comment by gfranciscani** [comment]
Fixed on branch gf-graph-canvas-fixes. Waiting for merge!

**Comment by ojvictor** [comment]
Fix Validado
