### ISSUE TITLE
Erro ao realizar o upload da base de dados

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#59]
A mensagem que aparece no console:

VM43:1 POST http://staging-ceweb.speed.dcc.ufmg.br/datasources 413 (Request Entity Too Large)
(anonymous) @ VM43:1
send @ jquery.js:9175
ajax @ jquery.js:8656
create @ new.js:14
triggerEvent @ ember.debug.js:30355
trigger @ ember.debug.js:50524
trigger @ ember.debug.js:49236
send @ ember.debug.js:29704
send @ ember.debug.js:33606
(anonymous) @ ember.debug.js:12178
flaggedInstrument @ ember.debug.js:20164
runRegisteredAction @ ember.debug.js:12177
run @ ember.debug.js:294
run @ ember.debug.js:23728
handler @ ember.debug.js:12164
(anonymous) @ ember.debug.js:43400
dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549
VM43:1 XHR finished loading: POST "http://staging-ceweb.speed.dcc.ufmg.br/datasources".

**Comment by michelboaventura** [comment]
O Nginx estava configurado com o tamanho padrão de upload máximo. Atualizei a configuração para 4GB max, testei aqui e funcionou!
