### ISSUE TITLE
Visualização: Termo sugerido no campo de sugestão não é ativado no grafo por mouse

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#60]
O termo sugerido no campo de pesquisa só é ativado no grafo quando se clica enter. 

Corrigir para que quando selecionarmos o termo, 
 a seleção do nodo no grafo seja automática.

**Comment by michelboaventura** [comment]
@gfranciscani

**Comment by gfranciscani** [comment]
Fixed on branch gf-graph-canvas-fixes. Waiting for merge!

**Comment by ojvictor** [comment]
Fix validado.
