### ISSUE TITLE
Faixa branca na parte de baixo da tela de home e base de dados

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#97]
- [ ]  Presença de uma faixa branca na parte inferior da tela home e base de dados.
![css_error_blank_band](https://cloud.githubusercontent.com/assets/6419508/26828703/07f51b84-4a99-11e7-80ad-2f558c3a71e9.png)

**Comment by mgonc** [comment]
esse problema é devido ao css da marimbondo, acho valido pedir para eles arrumarem. deixar o footer fixo
