### ISSUE TITLE
O campo de busca só funciona para o campo Nome

### ISSUE THREAD

**Issue by ojvictor** [michelboaventura/mj_data_explorer#98]
O campo de busca da ferramenta só funciona no atributo nome. Seja para base ou para filtro. 

O ideal é que funcionasse para todos os campos, desta forma o usuário pode buscar bases por autor ou por data. 
O mesmo para filtros, permitindo que o usuário filtre as execuções realizadas numa mesma data, vinculadas a um mesmo autor, etc.

**Comment by michelboaventura** [comment]
@ojvictor, acho que busca por autor não faz sentido nos dois casos pois o usuário só vê suas próprias coisas.

Na busca por data, não chegamos a fazer porque não pensamos uma forma boa de contornar a seguinte complexidade:

1. Se o usuário digita "06", deveríamos buscar esse valor em dia, mês, ano, hora e minuto?
2. Se ele digita "fev" ou "fevereiro" deveríamos entender que se trata de uma busca por mês, mas no caso de "feve" não.

Uma solução que havíamos pensado seria tratar a data como uma string como "Ter, 06 Jun 2017 13:22:32" e o que o usuário buscar e por coincidência casar aí dentro nós aceitamos como matching. O ponto negativo disso é que perdemos a possibilidade de buscar direto no banco (já que a data não é salva como string) e teríamos que retornar todos os elementos e fazer a buscar por "software".

O que você acha?

**Comment by ojvictor** [comment]
@michelboaventura Não teria como implementar aquelas buscas padronizadas por período? O usuário definiria uma data inicial e outra final e o sistema retornaria o período de matching?

**Comment by guerra** [comment]
@ojvictor isso é uma demanda que veio do pessoal do mj?

**Comment by ojvictor** [comment]
não @guerra
